### PR TITLE
Move pkg/pillar/api/ to sdk/go; create sdk/python

### PR DESCRIPTION
**Pull request by deitch**
As discussed in the email. 

This is more of a proposal. It does the following:

* creates an `sdk/<lang>/` dir for all of the output files (including python, go, etc.). 
    * keeps the python out of the root dir
    * keeps the go in its own package, as an "sdk"
    * puts all of the output in one place, easy to find
* makes the `Makefile` more DRY by removing repetition and automatically discovering `api/*/` subdirs
* updates the proto `go_package` directives to match
* updates `pkg/pillar/` to consume
* creates `make sdk` target that will build all known protobuf lang-specific files (and can be extended by adding to the variable list in the `Makefile`)

Requires some testing....

### CODE REVIEW

**Comment by rvs** [comment]
Hey @deitch seems like the pillar build is failing since the imported go code now exists outside of the pillar package. pkg/pillar is setup to build without network access (which I kind of like). Thus I think we either need to break that rule or re-vendor the code into pkg/pillar. Both of which will require talking to @zedvijay @eriknordmark and @kalyan-nidumolu to make sure we pick the most optimal workflow for folks who spend most of their time hacking on pillar

**Comment by deitch** [comment]
> Hey @deitch seems like the pillar build is failing since the imported go code now exists outside of the pillar package

Yeah, I saw that right after pushing. I can replicate it locally - took some digging to figure out exactly which part was failing - but I don't have an immediate answer. I spent some time mulling it over and trying different things. It is a limitation and a strength of the docker build, with its context root. 

When building `pkg/pillar` from its root via `docker build` (or `lkt pkg build`, which just wraps it), the only path it has access to is the docker context (`pkg/pillar`) or network. `sdk/go` is outside of that, thus accessible only via network. If this were built from the repo root, it would be an easy fix, but it is not. 

> pkg/pillar is setup to build without network access (which I kind of like)

I like it too, but it is _not_ set up to build without network access, see [build.yml#L7](https://github.com/zededa/eve/blob/master/pkg/pillar/build.yml#L7). It couldn't, since it downloads all of those golang packages.

>  Thus I think we either need to break that rule or re-vendor the code into pkg/pillar

When it comes down to it, we have two conflicting desires:

* Good engineering practice: Not make the canonical location of something shared (`api` or the generated go code) inside a client of it (`pkg/pillar`)
* Not have to vendor in (via network or prior command) the protobufs

By definition, not making the client as the canonical location of the shared means it has to consume it from elsewhere, either the same repo or another one. Building in docker means it doesn't matter if it is the same repo or another one, it has to get dependencies via network or another image.

I see several options:

1. Keep the generated go code as-is in `pkg/pillar`. This has all of the downsides discussed in moving `api` into here, but even worse in that it is actually inside a sub-project of the repo.
2. Keep the generated go code in `sdk`, but also vendor it into `pkg/pillar`. This isn't too bad, since we _already_ have to do a protobuf build step (`make proto-go`) before we can build `pkg/pillar`. I don't love the idea of it duplicating it in, but it isn't terrible.
3. Keep the generated go code in `sdk` and build it into a docker image, so that it can be consumed in a `FROM` step in `pkg/pillar/Dockerfile`, and use `PARSE_PKGS` to get the right hash. This requires the package to be in `sdk` (i.e. outside of `pkg/`), otherwise it would have the same problem as `pkg/pillar`. Doable, but a bit messy.
4. Keep the generated go code in `sdk`, and consume it via network. This means that to change the generated go code, you file one PR for changing the protobufs and generating the code, merge that, and then make changes to `pkg/pillar`.

The last is the "right thing to do". It encourages proper practices in terms of PR flow and separation of concerns, makes it very clear and easy for someone outside of `eve` to consume the API (and find godoc or other docs), makes it easy to add new languages, sets the groundwork for eventually moving `api` into a separate repo, while currently keeping both `api` and `pillar` in a single repo as we required. Nothing about "single repo" says, "must be in same directory and cannot PR separately." 

That having been said, we could do 2 or 3, if desired, although 3 is a convoluted way of getting to 4. go _already_ has an include mechanism, including getting packages from outside its current context. We should just use it, which means 4.

My recommendation here:

1. Re-vendor in so that everything works and can be merged in.
2. Remove re-vendoring, so that it is consumed the way all of the other packages in `pkg/pillar` are consumed.

Back to you @rvs :-)

**Comment by rvs** [comment]
Hey @deitch thanks for thinking through the options here. After talking to some of the folks exposed to this it is pretty clear that @nordmark is the only one managing the vendoring today. Everybody else just expects this to work out-of-the-box.

With that in mind, I think we should go ahead with option #2 (but also make sure that vendoring Makefil logic in pillar keeps functioning correctly).

Makes sense?

**Comment by deitch** [comment]
>  I think we should go ahead with option 2 (but also make sure that vendoring Makefil logic in pillar keeps functioning correctly)

That basically is the first step of the 2 I suggested above. Let's do that. It is a good first step towards eventually removing it from being vendored into `pkg/pillar`, and that can happen when we are ready.

In the meantime...

> Everybody else just expects this to work out-of-the-box.

Not sure what you mean? Do they consume it elsewhere? Or is it that they just build `pkg/pillar` and don't think about the `api` or consume it directly at all?

**Comment by deitch** [comment]
Updated. 

* The targets `make proto-go` and `make proto-python` (or any other language) will _only_ compile those files into `sdk/`.
* The target `make sdk` will compile for _all_ supported languages (based on the list in the `Makefile`, currently only `go` and `python`), **and** vendor them into the proper place in `pkg/pillar/vendor` so they are available.

**Comment by deitch** [comment]
Make sense @rvs and @eriknordmark ?

**Comment by deitch** [comment]
Build now is succeeding here, but `yetus` is failing, probably on the python stuff. Any idea how we exempt the generated code in `sdk/python/` from it?

**Comment by rvs** [comment]
I find it kind of hilarious that pylint is so unhappy about protobuf generated code. @aw-was-here what would be your recommendation here?

**Comment by aw-zededa** [comment]
For generated code, it's better to just put the proper regex into .yetus-excludes  so that Yetus will (mostly) stop caring about it.  (It's worth noting that Google's default pylint settings are extremely generous because they had too much broken code.  I wouldn't be surprised if protobuf wasn't cleaned up as a result.)

**Comment by deitch** [comment]
> it's better to just put the proper regex into .yetus-excludes

Done, thank you. Hopefully I got it right. Will watch CI.

**Comment by deitch** [comment]
Well, I thought I got it right. I add 

```
^sdk/
```

to `.yetus-excludes`, but it appeared still to include it. What did I do wrong @aw-zededa ?

**Comment by aw-zededa** [comment]
Congrats, you found a bug. :)

Filed https://issues.apache.org/jira/browse/YETUS-868 .  The way to work around this is to commit the excludes file first, then re-run. But I'm confident that your change will work. :)

**Comment by deitch** [comment]
> Congrats, you found a bug. :)

LOL! I sure am glad I posted here right away rather than spending hours going down a rabbit hole to figure out what I did wrong!

> The way to work around this is to commit the excludes file first, then re-run.

Meaning a separate PR for just the excludes, then this one?

**Comment by aw-was-here** [comment]
> LOL! I sure am glad I posted here right away rather than spending hours going down a rabbit hole to figure out what I did wrong!

The joys of new features.  (The exclusion bit was added to Yetus in the past month or so!)  

> Meaning a separate PR for just the excludes, then this one?

Yup. The file only gets read on launch so if the excludes file already has ^sdk/ in it, then anything in that directory should get ignored.

**Comment by deitch** [comment]
See #47 .

**Comment by deitch** [comment]
Rebased after yetus fix in #47 and rerunning tests.

**Comment by deitch** [comment]
Booyah! It passed! 

@rvs / @eriknordmark , we good to go on this?

**Comment by rvs** [comment]
LGTM! Merged -- thanks for all the work on this @deitch -- I can now send a few additional Makefile logic changes on top of this one.

**Comment by deitch** [comment]
Excellent!

**Pull request merged**
