### PR TITLE
Merging zededa/api into eve

### PR DESCRIPTION
**Pull request by rvs**
Guys, this is a proposed merge of zededa/api into eve.

As you can see -- the api folder stays at the top level of the repo and the generated go files are going under pkg/pillar/api

We can talk about where the python generated files need to go, but this is good enough to evaluate the proposed scheme for now.

If we like what is proposed here -- I'll polish Makefile magic and pull it to the top level of eve repo

### CODE REVIEW

**Comment by deitch** [comment]
I’m not convinced that `api` should be merged into `eve`. It’s a spec definition, as well as message formats in protobuf as part of that spec. 

Should that not be an independent thing that gets consumed by eve (or pillar within eve), Adam and zedcloud? It has its own lifecycle, could be consumed in other places as well. 

What’s the downside of keeping it independent?

**Comment by rvs** [comment]
Hey @deitch totally agree with you and @zedvijay that long term API needs to end up as a separate repo (with its own governance and release cycle). This will happen when we clean it up enough. For the next few month (while that cleanup is happening) it is just easier (mechanically) for us to manage it here. Once we're ready to declare it v2 -- we'll pull it out into a separate repo.

Makes sense?

**Comment by deitch** [comment]
@rvs I am going to stand my ground on this one (and you know I don't push back just for the fun of it) for a few reasons:

* eve is a client of api; so are zedcloud, adam and potentially many others. Not only is it challenging to have clients consume from other clients when it could easily be a shared component in its own repo, it sets us up for more trouble in the future.
* it discourages others from leveraging the api in ways we cannot think of because it is embedded in eve, even if directly consumable. We want to make it very easy to use/manipulate/update/propose/etc the api to open all sorts of new things. Embedding it in another repo discourages others from doing so with it.
* The CI lifecycles for the two are very different. Eve builds images. Very shortly, I expect we will have longer and slower CI runs for eve, since it will have to build images and boot them, etc. We do not want to slow down api changes or tests because of something much larger and heavier. Think of a PR to discuss API changes that affects only docs, or adds new protobuf messages. We should have very fast cycle times on those, but do we really want to wait the 20 mins or 60 mins or more for a full cycle through of CI on eve? The alternative would be bypassing CI, but that is opening up the doors of Hades.
* The interested parties have only partial overlap. Only some of those discussing eve and interested in it will have interest in api and vice versa. The issues and PRs spaces will get very messy. 

If they weren't yet split, I would encourage the split as soon as possible, but maybe not _today_. But if they already are split? I would leave them.

When it comes down to it, my biggest concern is incentives (and my psychologist wife laughs again at this engineer talking about soft human factors): making it easy for people to get involved and active in ways we don't expect, and not discouraging them.

What is the strong driver on merging them? Is it _really_ mechanically easier together? 

Like to hear your viewpoint on this. @zedvijay?

**Comment by rvs** [comment]
@deitch I actually agree with every single one of your arguments, but the problem is:

> If they weren't yet split, I would encourage the split as soon as possible, but maybe not today. But if they already are split? I would leave them.

No, they are NOT effectively split. Even if they sit in different repos, they are unfortunately (logically not split) simply because of the amount of gymnastics on the build/update side it takes today to re-vendor in pillar.

Think of it this way -- the other repo is a mirage in a way. The actual API lives in vendor and what we're doing with this patch is simply moving files from vendor to something under pkg/pillar.

So in fact, we're in agreement when it comes to:

> If they weren't yet split, I would encourage the split as soon as possible, but maybe not today.

So yes -- not today. But we'll start working on it ASAP, although sadly I don't think we will make an LF transition deadline.

**Pull request merged**
