### PR TITLE
Moving to Go 1.12

### PR DESCRIPTION
**Pull request by rvs**
Please note that as part of this I had to simplify how we import linuxkit and manifest-tool. We can no longer rely on importing hacks via Gopkg.toml AND since go doesn't allow importing of the main modules I had to import actual files. I've updated LICENSE and NOTICE accordingly.

Another annoying feature of Go modules as it happens is the fact that they mandate the version IDs to be used on github. Thus I couldn't just import linuxkit v0.7 and had to do v0.0.0-20190417213831-4f4f7feae125 instead.

Other than that -- this represents a pretty significant cleanup and now allows out-of-tree builds, remapping of dependencies, etc.

I'll follow up with additional cleanups of Dockerfile in pillar

### CODE REVIEW

**Review by eriknordmark — COMMENTED** [review]
LGTM

**Comment by rvs** [comment]
Thanks @nordmark 

@deitch please take a look and let us know what do you think -- I'd like to merge this in ASAP to give a bit of baking time before we cut over on 5/10.

**Comment by deitch** [comment]
Is there any reason not to just download the released binaries from https://github.com/linuxkit/linuxkit/releases and https://github.com/estesp/manifest-tool/releases ? Unless we absolutely need to build from source, why vendor in the entire source tree? 

manifest-tool is just about 1.0.0, and linuxkit v0.7 is fairly recent.

**Comment by rvs** [comment]
Yup @deitch noticed manfiest-tools going 1.0.0 pretty soon -- that we can pull once they actually release. I need a few things in linuxkit 0.7 so that's why. And speaking of needing a few things: that's the idea behind pulling the source -- @gianlzed and I wanted to hack it right in our tree (and later upstream the patches). That has gotten to be much lower priority. Certainly for manifest-tool  we can just pull the binary down. For linuxkit I actually do have a few PRs I need to apply to the source I'm pulling down so keeping it in source form may make sense for now.

So here's what I'd propose -- lets merge the PR in its current form and then we can decide whether switching to downloading binaries would make sense down the road (once I upstream my build stuff into lk).

Makes sense @deitch ?

**Comment by deitch** [comment]
> I need a few things in linuxkit 0.7

0.7 has been released. Or did you mean we need to add a few things to 0.7, ie beyond it? And if so, is it things in master of lkt but not yet released? Or additional patches?

> lower priority now

Then please let’s not pull in all the code now. We can have a separate discussion when we actually need it. 

I can almost guarantee you that our copies of the source will get out of sync very quickly. If we have PRs, let’s get them on the master ASAP.

I’m deeply worried that we are creating a boondoggle by downloading all of the code and committing it. People will start to change things and getting out of it will be weeks or more of work. 

Unless we absolutely must, can we please just `go get` or at worst use modules to get it? I see the yawning abyss of unending maintenance here. Maybe I’ve been hurt too many times by it. :-)

**Comment by deitch** [comment]
In any case, if we _must_ use a non-released version, can we not just stick with the go way of doing it?

```sh
$ TMPGOPATH=$PWD/.go    # or pick some other path, or even use the basic GOPATH
$ GO111MODULE=off GOPATH=$TMPGOPATH go get -u github.com/linuxkit/linuxkit/src/cmd/linuxkit
$ GO111MODULE=off GOPATH=$TMPGOPATH go build -o bin/linuxkit github.com/linuxkit/linuxkit/src/cmd/linuxkit
```

No need to version in everything.

**Pull request closed without merging**
