### PR TITLE
Merge https://github.com/zededa/go-provision/pull/351

### PR DESCRIPTION
**Pull request by rvs**
Signed-off-by: Roman Shaposhnik <rvs@zededa.com>

### CODE REVIEW

**Comment by deitch** [comment]
@rvs commented:

> I think we still have an issue on Mac OS:

```
$ make build
....
go install github.com/zededa/go-provision/zedbox: mkdir /Users: permission denied
```

> This seems to be on account of go build command having -o /Users/roman/... option while inside of the container it maps into /home/roman.
>
> I think we should just run go install .../zedbox in the container and then copy the binary outside the container into dist

**Comment by deitch** [comment]
> This seems to be on account of go build command having -o /Users/roman/... option while inside of the container it maps into /home/roman

Ah, ok, now I see it. 

I have a much simpler solution: just relativize (yes, relativize really [is a word](https://en.oxforddictionaries.com/definition/relativize)) the `DISTDIR`, and the target, which is the "right thing to do" from a Makefile perspective.

[Here](https://gist.github.com/deitch/b6b7188fd31c642d61b24a594abeb0f5) is a proposed `Makefile` (but I cannot implement it, because now this is a PR from your branch).

It uses `dist/amd64/zedbox` as an actual target, the way `Makefile` is supposed to. It also uses relative directories for building.

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by rvs** [comment]
@deitch I merged this one -- please create addition PRs for the Makefile changes you proposed

**Comment by deitch** [comment]
@rvs  done. Added #30

**Pull request merged**
