### PR TITLE
Markdownlint config

### PR DESCRIPTION
**Pull request by deitch**
Prevent markdownlint from complaining about line length.

### CODE REVIEW

**Comment by rvs** [comment]
Hey @deitch now that Yetus is fixed, it looks like it found legitimate issue with your yml

**Comment by deitch** [comment]
And so it did. That’s pretty funny as it errored on the markdown lint config file. I also don’t agree with its view that every yml *must* start with a comment line `—-` but I don’t mind adding it here

**Comment by deitch** [comment]
That should do it (I hope)

**Comment by deitch** [comment]
Phew. That worked.

**Pull request merged**
